# Generated by Django 4.2.7 on 2023-11-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("logo", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("image", models.ImageField(upload_to="media")),
                ("comment", models.TextField()),
                ("post", models.CharField(max_length=300)),
                ("star", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="siteinformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("logo", models.ImageField(upload_to="media")),
                ("description", models.TextField(blank=True)),
                ("email", models.EmailField(max_length=20)),
                ("twitter", models.URLField(blank=True, max_length=500)),
                ("facebook", models.URLField(blank=True, max_length=500)),
                ("instagram", models.URLField(blank=True, max_length=500)),
                ("youtube", models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("image", models.ImageField(upload_to="media")),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("rank", models.IntegerField()),
            ],
        ),
    ]
