# Generated by Django 4.2.7 on 2023-12-01 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_awesome_bestseller_featuredcategory_logo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logo",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="logo",
            name="slug",
        ),
    ]
