# Generated by Django 4.2.7 on 2023-12-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_logo_logo_remove_logo_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredcategory",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="featuredcategory",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="siteinformation",
            name="logo",
        ),
        migrations.AddField(
            model_name="siteinformation",
            name="url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
