# Generated by Django 4.2.7 on 2023-12-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_featuredcategory_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clientlogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, unique=True)),
                ("image", models.ImageField(upload_to="media")),
            ],
        ),
        migrations.RemoveField(
            model_name="awesome",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="featuredcategory",
            name="rank",
        ),
    ]
